---
# ====== Application: APEXToGo ===============================
id: 104
identification: 
  name: APEXToGo
  alias: APEXTOGO
  version: 24.2.0
  application-group: Sample Apps # 26172205414546942

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Username Only # 1935007971896997368

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions
  maximum-session-length: 43200
  maximum-session-idle-time: 28800

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: PROJECT

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image and Text
  image-url: '#APP_FILES#icons/app-icon-144-rounded.png'
  text: APEXToGo

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  theme-color: '#ffffff'
  ios-status-bar-style: Default
  app-description: Oracle APEX Mobile Sample Application
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 9500 Push Notifications Credentials # 43885502583707444

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:HOME:&APP_SESSION.::&DEBUG.:::'
    page: HOME

  login-url: 
    url: 'f?p=&APP_ID.:WELCOME:&APP_SESSION.::&DEBUG.:::'
    page: WELCOME

navigation-menu: 
  list-template: Top Navigation Tabs
  template-options: 
  - '#DEFAULT#'
  - t-NavTabs--inlineLabels-lg
  - t-NavTabs--hiddenLabels-sm
  list-position: Top
  list: Navigation Menu # 166424854541130361

navigation-bar: 
  implementation: List
  list: Navigation Bar # 166708737345130741
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#APP_FILES#js/apextogo#MIN#.js'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_FILES#css/apextogo#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: true

subscription: 
  version-number: 45077787266574

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: APEXToGo

component-settings: 
- # ====== Component Setting: NATIVE_BOSS ======================
  id: 34625053834868989
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 187833978

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 37676596743285138
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 37167672045927

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 37676935249285138
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 37167672045928

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 37677366437285139
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 37167672045928

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 166420752611130354
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 166421017347130354
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 166421359067130354
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 166421613279130355
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 166421983305130355
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 166422310842130355
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 166422596457130356
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 166422825863130356
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 166423137649130356
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 37165931336889

- # ====== Component Setting: NATIVE_IR ========================
  id: 166423509754130357
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 37165931336889

pwa-shortcuts: 
- # ====== PWA Shortcut: Home ==================================
  id: 718530370165904915
  identification: 
    name: Home

  layout: 
    sequence: 10

  link: 
    target: 
      url: 'f?p=&APP_ID.:1:&SESSION.'
      page: 1 # Welcome

  configuration: 
    icon-url: pwa/shortcut-icon-10.png

- # ====== PWA Shortcut: Cart ==================================
  id: 718532198099910631
  identification: 
    name: Cart

  layout: 
    sequence: 30

  link: 
    target: 
      url: 'f?p=&APP_ID.:7:&SESSION.'
      page: 7 # Item Details

  configuration: 
    icon-url: pwa/shortcut-icon-30.png

- # ====== PWA Shortcut: Orders ================================
  id: 718533369262914648
  identification: 
    name: Orders

  layout: 
    sequence: 40

  link: 
    target: 
      url: 'f?p=&APP_ID.:4:&SESSION.'
      page: 4 # Home

  configuration: 
    icon-url: pwa/shortcut-icon-40.png

pwa-screenshots: 
- # ====== PWA Screenshot: screenshot-2.png ====================
  id: 84372376258256148
  label: 
    label: screenshot-2.png

  layout: 
    sequence: 20

  configuration: 
    screenshot-url: pwa/screenshot-2.png

- # ====== PWA Screenshot: screenshot-3.png ====================
  id: 84372876397256854
  label: 
    label: screenshot-3.png

  layout: 
    sequence: 30

  configuration: 
    screenshot-url: pwa/screenshot-3.png

- # ====== PWA Screenshot: screenshot-4.png ====================
  id: 84373398713257918
  label: 
    label: screenshot-4.png

  layout: 
    sequence: 40

  configuration: 
    screenshot-url: pwa/screenshot-4.png

- # ====== PWA Screenshot: screenshot-1.png ====================
  id: 84374166768259589
  label: 
    label: screenshot-1.png

  layout: 
    sequence: 10

  configuration: 
    screenshot-url: pwa/screenshot-1.png

